### PR TITLE
JSON board support and Bootloader support

### PR DESCRIPTION
**Pull request by CorvusPrudens**
This PR adds JSON board support along with support for the Daisy bootloader. The repo has been significantly restructured, now relying on `hvcc` and `json2daisy` as external python modules downloaded from pypi. It also brings in the recent support for various sensors.

### CODE REVIEW

**Comment by beserge** [comment]
There's more testing to be done, but here's a first round of stuff I found:

# Install
- [ ] Had to change python3 to python in install.sh. This is a peculiarity with my setup but we should probably let users know this might be something they have to tweak
- [ ] venv drops activate in `pd_env/Scripts' so I had to change install.sh to reflect that. 
Once I made those changes everything worked great!

# Usage
- [ ] In the readme under usage you list (seed, pod, patch) as the available boards. This should be updated.

# Pod
- [ ] The readme lists CV, gate and spdt that the pod doesn't have.
- [ ] led2 seems to have its blue stuck on.
- [ ] I tried sending directly to led1 and got the error: `clamp not declared in this scope` . Not sure if I was using that improperly... Perhaps that has to be updated to fclamp. Not sure.

# Patch
- [ ] Knobs are backwards! I'm pretty sure the controls have a reverse Init argument or something.
- [ ] The Gate IO worked fine just passing through, but the gateins don't trigger the envelopes for me in the example.

# Petal
- [ ] There are some leds stuck on: fs 2, 3, 4. enc 4, 7, 8.

# Field
- [ ] The keyboard leds are jumbled, the names don't match the leds.
- [ ] The key names are jumbled as well. The field has a mapping from int -> key / led that isn't 100% intuitive so it seems like you just naively passed the int along without mapping.
- [ ] Gateout doesn't work. Tried passing through gatein and sending it a metro.

# patch.Init()

This one works great! Nice work!


# Etc

- [ ] The patches that use the line envelope thing crackle. This happens on the desktop as well, but it would definitely be offputting to newbies.


# Day 2 stuff (don't worry about this for now)
- [ ] Should consider having the leds have some default behavior if the user doesn't explicitly use them.
- [ ] I'm sure we'll also thinking about doing some default oled stuff the same way oopsy does.

**Comment by stephenhensley** [comment]
>The patches that use the line envelope thing crackle. This happens on the desktop as well, but it would definitely be offputting to newbies.

This can be resolved by using `line~` instead -- essentially using any non`~` objects for things like amplitude, delay time, etc. will result in noticeable zippering effects (quantization error).

**Comment by beserge** [comment]
Field issues are confirmed fixed. The petal still has led issues. There's a PD file attached to the trello card you can use to test that.
I don't have a patch and pod on hand to test with atm, but based on reading over the changes I strongly suspect those issues are fixed.

The new install script worked great. We should add a note in the readme about the Scripts folder rather than bin on windows.

**Comment by stephenhensley** [comment]
let's do it!

**Pull request merged**
